services:
  postgres:
    image: postgres:16
    container_name: pmsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=DB_NAME
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - pmsdb_volume:/var/lib/postgresql/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./02-create-admin.sql:/docker-entrypoint-initdb.d/02-create-admin.sql
volumes:
  pmsdb_volume:
    driver: local